//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class choice extends JPanel {
    private JButton jcomp1;
    private JLabel jcomp2;
    private JButton jcomp3;

    public choice() {
        //construct components
        jcomp1 = new JButton ("Doctor");
        jcomp2 = new JLabel ("Add who's details");
        jcomp3 = new JButton ("Patient");

        //adjust size and set layout
        setPreferredSize (new Dimension (601, 350));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (180, 140, 100, 25);
        jcomp2.setBounds (245, 75, 115, 50);
        jcomp3.setBounds (305, 140, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("choice");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new choice());
        frame.pack();
        frame.setVisible (true);
    }
}
