//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class doctor_gui extends JPanel {
    private JTextField jcomp1;
    private JButton jcomp2;
    private JLabel jcomp3;
    private JLabel jcomp4;
    private JSlider jcomp5;
    private JTextField jcomp6;
    private JLabel jcomp7;
    private static Person p;
    private static JFrame frame;
    private static boolean proceed = false;

    public doctor_gui() {
        //construct components
        jcomp1 = new JTextField (5);
        jcomp2 = new JButton ("Submit Details");
        jcomp3 = new JLabel ("Enter Doctor's name");
        jcomp4 = new JLabel ("Enter Doctor's age");
        jcomp5 = new JSlider (20, 100);
        jcomp6 = new JTextField (5);
        jcomp7 = new JLabel ("Enter Doctor's speciality");

        //set components properties
        jcomp5.setOrientation (JSlider.HORIZONTAL);
        jcomp5.setMinorTickSpacing (1);
        jcomp5.setMajorTickSpacing (10);
        jcomp5.setPaintTicks (true);
        jcomp5.setPaintLabels (true);

        //adjust size and set layout
        setPreferredSize (new Dimension (601, 350));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (150, 35, 260, 30);
        jcomp2.setBounds (235, 230, 120, 25);
        jcomp3.setBounds (15, 35, 135, 30);
        jcomp4.setBounds (15, 100, 120, 25);
        jcomp5.setBounds (135, 90, 450, 45);
        jcomp6.setBounds (185, 155, 255, 25);
        jcomp7.setBounds (15, 155, 155, 25);

        jcomp2.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {                p = PersonFactory.createPerson("doctor", jcomp1.getText(), jcomp5.getValue(), jcomp6.getText());  
                proceed = true;
                frame.dispose();
            }
        });
    }


    public static Person start_gui() {
        frame = new JFrame ("Doctor Details");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new doctor_gui());
        frame.pack();
        frame.setVisible (true);
        while(!proceed)
        {
            System.out.print("");
        }
        return p;
    }
}
