//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class patient_gui extends JPanel {
    private JLabel jcomp1;
    private JLabel jcomp2;
    private JTextField jcomp3;
    private JSlider jcomp4;
    private JButton jcomp5;
    private static Person p;
    private static JFrame frame;
    private static boolean proceed = false;

    public patient_gui() {
        //construct components
        jcomp1 = new JLabel ("Patient Name");
        jcomp2 = new JLabel ("Patient Age");
        jcomp3 = new JTextField (5);
        jcomp4 = new JSlider (1, 100);
        jcomp5 = new JButton ("Submit Details");

        jcomp4.setOrientation (JSlider.HORIZONTAL);
        jcomp4.setMinorTickSpacing (1);
        jcomp4.setMajorTickSpacing (5);
        jcomp4.setPaintTicks (true);
        jcomp4.setPaintLabels (true);

        //adjust size and set layout
        setPreferredSize (new Dimension (601, 350));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (25, 65, 100, 25);
        jcomp2.setBounds (25, 105, 100, 25);
        jcomp3.setBounds (110, 65, 220, 30);
        jcomp4.setBounds (110, 105, 450, 30);
        jcomp5.setBounds (235, 180, 120, 25);

        jcomp5.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {                
                p = PersonFactory.createPerson("patient", jcomp3.getText(), jcomp4.getValue());  
                proceed = true;
                frame.dispose();
            }
        });
    }


    public static Person start_gui() {
        frame = new JFrame("Patient Deails");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new patient_gui());
        frame.pack();
        frame.setVisible (true);
        while(!proceed)
        {
            System.out.print("");
        }
        return p;
    }
}
